### ISSUE TITLE
AttributeError: '_SpecialEuclidean3Vectors' object has no attribute 'left_canonical_metric'

### ISSUE THREAD

**Issue by hpbtql** [mfazampour/ProRegGAN#1]
Dear Prof. Mohammad Farid Azampour,

Your work _Multitask Weakly Supervised Generative Network for MR-US Registration_ on TMI is truly impressive. However, when I ran your code, I encountered the following error:

```
codes/ProRegGAN/venv/bin/python 
codes/ProRegGAN/train.py 
INFO: Using numpy backend
Traceback (most recent call last):
  File "codes/ProRegGAN/train.py", line 16, in <module>
    from options.train_options import TrainOptions
  File "codes/ProRegGAN/options/train_options.py", line 1, in <module>
    from .base_options import BaseOptions
  File "codes/ProRegGAN/options/base_options.py", line 5, in <module>
    import models
  File "codes/ProRegGAN/models/__init__.py", line 22, in <module>
    from models.base_model import BaseModel
  File "codes/ProRegGAN/models/base_model.py", line 11, in <module>
    from models import networks
  File "codes/ProRegGAN/models/networks.py", line 20, in <module>
    from util import se3
  File "codes/ProRegGAN/util/se3.py", line 11, in <module>
    metric=SE3.left_canonical_metric,
AttributeError: '_SpecialEuclidean3Vectors' object has no attribute 'left_canonical_metric'
```

Looking forward to fixing this.

**Comment by hpbtql** [comment]
add `SE3.left_canonical_metric = SE3.metric` can slove this.
